### ISSUE TITLE
Error in line 5 in main.py

### ISSUE THREAD

**Issue by ahinojos0029** [Nemika-Haj/BytesBump#3]
I keep getting an error in that line, it says 
![Screenshot 2021-06-22 9 21 15 AM](https://user-images.githubusercontent.com/79881161/122963565-3d4e3980-d33b-11eb-8c29-f2d6a9e63aad.png)

**Comment by Nemika-Haj** [comment]
On your Repl, click this icon at the left side of the screen
![image](https://user-images.githubusercontent.com/33802693/122970522-b62eaf00-d396-11eb-9108-fd7cb15d7ec4.png)
Then search for PyYAML, click the add icon, and run again.
